name: Tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Check project version
      run: make info
    - name: Run tests
      run: make test

  build:
    needs: run-tests
    strategy:
      matrix:
        python: [ '3.10', '3.11', '3.12' ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Check project version
        run: make info
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: make build
      - name: Twine check
        run: make twine-check
